[package]
name = "gtk-rs-state"
version = "0.2.0"
authors = ["Phaiax <phaiax-git@invisibletower.de>"]
edition = "2018"

[dependencies]
lazy_static = "*"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_10"]

[dependencies.glib]
version = "0.6.0"
