[package]
name = "gtktest"
version = "0.1.0"
authors = ["Phaiax <phaiax-git@invisibletower.de>"]
edition = "2018"

[dependencies]
lazy_static = "*"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_10"]

[dependencies.gobject-sys]
version = "0.7.0"
